all:studenthub  manip modiefier recherche Saisir Supprimer Trier executable exe
exe:
	./studenthub
executable:studenthub  manip modiefier recherche Saisir Supprimer Trier
	gcc -o studenthub studenthub.o  manip.o modiefier.o recherche.o Saisir.o Supprimer.o Trier.o
studenthub:
	gcc -c studenthub.c

manip:
	gcc -c manip.c
Modifier:
	gcc -c Modifier.c
Recherche:
	gcc -c Recherche.c
Saisir:

	gcc -c Saisir.c
Supprimer:
	gcc -c Supprimer.c
Trier:
	gcc -c Trier.c
clear:
	rm  rm -f studenthub *.o

